In [25]:
import numpy, pandas

In [26]:
# For a Numpy object

a = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

# Reference
b = a

a[0,0] = 999

print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[999   2   3]
 [  4   5   6]
 [  7   8   9]]
[[999   2   3]
 [  4   5   6]
 [  7   8   9]]


In [27]:
# Copy a Numpy object

a = numpy.array([[1,2,3],[4,5,6],[7,8,9]])

b = a.copy()

a[0,0] = 999

print(a)
print(b)

[[999   2   3]
 [  4   5   6]
 [  7   8   9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# For a Dataframe

a = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
df = pandas.DataFrame(a, index = ["A1","A2","A3"], columns = ["B1", "B2", "B3"])
display(df)

B1  B2  B3
A1   1   2   3
A2   4   5   6
A3   7   8   9

In [29]:
df1 = df

df["B1"]=[99,99,99]

display(df)
display(df1)


B1  B2  B3
A1  99   2   3
A2  99   5   6
A3  99   8   9

B1  B2  B3
A1  99   2   3
A2  99   5   6
A3  99   8   9

In [30]:
# Copy a Dataframe
a = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
df = pandas.DataFrame(a, index = ["A1","A2","A3"], columns = ["B1", "B2", "B3"]) # the values in a are copied into df
display(df)

df2 = df.copy()

df["B1"]=[99,99,99]

display(df)
display(df2)

a[0][1] = 99
display(a)
display(df)


B1  B2  B3
A1   1   2   3
A2   4   5   6
A3   7   8   9

B1  B2  B3
A1  99   2   3
A2  99   5   6
A3  99   8   9

B1  B2  B3
A1   1   2   3
A2   4   5   6
A3   7   8   9

array([[ 1, 99,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

B1  B2  B3
A1  99   2   3
A2  99   5   6
A3  99   8   9

In [31]:
# With iloc
df2 = df.iloc[1,1] #value is copied
print(df2)

df["B2"]=[0,0,0]
print(df)
print(df2)

5
    B1  B2  B3
A1  99   0   3
A2  99   0   6
A3  99   0   9
5


In [32]:
# With loc
display(df)
df3 = df.loc[df['B3'] > 3]
display(df3)

df["B3"]=[10,10,10]
display(df)
display(df3)

B1  B2  B3
A1  99   0   3
A2  99   0   6
A3  99   0   9

B1  B2  B3
A2  99   0   6
A3  99   0   9

B1  B2  B3
A1  99   0  10
A2  99   0  10
A3  99   0  10

B1  B2  B3
A2  99   0   6
A3  99   0   9